backend:
  name: github
  repo: siegenom/siegenom.github.io
  branch: main
  auth_type: pkce

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "test"
    label: "Test"
    folder: "src/content/test"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }