name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write # gh-pages ブランチへの書き込み権限を付与

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # gh-pages へデプロイするために完全な履歴が必要な場合

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # またはプロジェクトで使用しているNode.jsのバージョン

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: List built files
        run: ls -R ./dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # cname: example.com # カスタムドメインを使用する場合
          # ここに他の設定（例: exclude, force_orphan）を追加できます
          force_orphan: true
