name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # main ブランチにプッシュされたときにトリガー

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v2
        with:
          path: . # プロジェクトのルートディレクトリ
          node-version: 20 # Astroが推奨するNode.jsのバージョン
          package-manager: npm # 使用するパッケージマネージャー